# Generated by Django 4.0.4 on 2022-05-29 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PrinterProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='RepairCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.printerproducer')),
            ],
        ),
        migrations.CreateModel(
            name='PrinterModelSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.printerproducer')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryPrinter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
                ('place', models.TextField(blank=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.factory')),
                ('model_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.printermodelseries')),
            ],
        ),
        migrations.CreateModel(
            name='Cartrige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('quantity', models.IntegerField()),
                ('min_quantity', models.IntegerField()),
                ('alert_quantity', models.BooleanField(default=False)),
                ('model_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.printermodelseries')),
            ],
        ),
    ]
