# Generated by Django 4.0.4 on 2022-06-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cartrige_model_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartrige',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
